/* Editor theme + design switcher.
 *
 * Two orthogonal axes drive the editor chrome:
 *
 *   1. THEME  — System / Light / Dark / Retro. The user's brightness
 *      mode preference. Persists at localStorage["editor.theme"].
 *      Changing the theme pill always resets the chrome to that
 *      built-in look (see (3) below for why).
 *
 *   2. DESIGN — null | violet | mono | paper | espresso | coral |
 *      ember | vinyl | scarlet | glacier | phosphor | hornet | prism.
 *      An optional decorative palette inspired by various design
 *      systems. Persists at localStorage["editor.design"]. When set,
 *      the design wins visually — the theme axis still has a value
 *      underneath but is not what's painting the chrome.
 *
 * Both axes apply through a single `data-theme` attribute on <html>:
 * the resolved string is the design (if any), else the resolved theme.
 * CSS for built-ins lives at the bottom of index.css; CSS for designs
 * lives in styles/themes.css (generated by tools/gen-themes.mjs).
 *
 * (3) Why does picking a theme clear the design? A user clicking
 * "Light" expects to see Light. If the design "Violet" was overriding,
 * the click would be invisible — confusing. Resetting design when the
 * theme axis changes preserves the "click → see change" journey.
 *
 * Migration: older localStorage values "default" and the design names
 * stored under "editor.theme" are read transparently and split into
 * the right axis on first load. */

/** Theme axis values. Includes "system", which resolves at apply time. */
export type ThemePreference = "system" | "light" | "dark" | "retro";

/** Design axis values. */
export type Design =
  | "violet" | "mono" | "paper" | "espresso" | "coral" | "ember"
  | "vinyl" | "scarlet" | "glacier" | "phosphor" | "hornet" | "prism";

/** Resolved chrome — what `data-theme` actually gets set to. */
export type ResolvedTheme = "light" | "dark" | "retro" | Design;

/** Picker metadata — `swatch` is a 4-color preview ([bg, surface,
 *  brand, ink]). Used by Settings + foot-pill UIs. */
export type ThemeMeta = {
  name: ThemePreference;
  label: string;
  swatch: readonly [string, string, string, string];
};
export type DesignMeta = {
  name: Design;
  label: string;
  /** "light" or "dark" controls grouping in the design picker. */
  kind: "light" | "dark";
  swatch: readonly [string, string, string, string];
};

/** The four built-in theme pills. Stable order — pickers render in
 *  this order. */
export const themes: readonly ThemeMeta[] = [
  { name: "system", label: "System", swatch: ["#faf9f5", "#14110d", "#c96442", "#1a1a1a"] },
  { name: "light",  label: "Light",  swatch: ["#faf9f5", "#ffffff", "#c96442", "#0f0c08"] },
  { name: "dark",   label: "Dark",   swatch: ["#14110d", "#1f1c17", "#e88d6f", "#f5f2eb"] },
  { name: "retro",  label: "Retro",  swatch: ["#e5d4b6", "#fffaf0", "#f44e1c", "#1c223a"] },
];

/** The 12 decorative designs — six light, six dark. */
export const designs: readonly DesignMeta[] = [
  { name: "violet",   label: "Violet",   kind: "light", swatch: ["#ffffff", "#f4f3fb", "#533afd", "#061b31"] },
  { name: "mono",     label: "Mono",     kind: "light", swatch: ["#ffffff", "#ebebeb", "#171717", "#666666"] },
  { name: "paper",    label: "Paper",    kind: "light", swatch: ["#fafaf9", "#f6f5f4", "#7b3ff2", "#37352f"] },
  { name: "espresso", label: "Espresso", kind: "light", swatch: ["#f2f0eb", "#ffffff", "#006241", "#1e3932"] },
  { name: "coral",    label: "Coral",    kind: "light", swatch: ["#fbfbf9", "#f6f6f3", "#e60023", "#211922"] },
  { name: "ember",    label: "Ember",    kind: "light", swatch: ["#f7f7f4", "#efeee8", "#f54e00", "#26251e"] },
  { name: "vinyl",    label: "Vinyl",    kind: "dark",  swatch: ["#121212", "#181818", "#1ed760", "#ffffff"] },
  { name: "scarlet",  label: "Scarlet",  kind: "dark",  swatch: ["#181818", "#303030", "#da291c", "#ffffff"] },
  { name: "glacier",  label: "Glacier",  kind: "dark",  swatch: ["#010102", "#141516", "#5e6ad2", "#f7f8f8"] },
  { name: "phosphor", label: "Phosphor", kind: "dark",  swatch: ["#000000", "#1a1a1a", "#76b900", "#ffffff"] },
  { name: "hornet",   label: "Hornet",   kind: "dark",  swatch: ["#000000", "#202020", "#ffc000", "#ffffff"] },
  { name: "prism",    label: "Prism",    kind: "dark",  swatch: ["#090909", "#141414", "#d44df0", "#ffffff"] },
];

const THEME_NAMES: ReadonlySet<ThemePreference> = new Set(themes.map((t) => t.name));
const DESIGN_NAMES: ReadonlySet<Design> = new Set(designs.map((d) => d.name));

const KEY_THEME = "editor.theme";
const KEY_DESIGN = "editor.design";
const EVENT_THEME = "editor-theme-change";
const EVENT_DESIGN = "editor-design-change";

function isTheme(v: unknown): v is ThemePreference {
  return typeof v === "string" && THEME_NAMES.has(v as ThemePreference);
}
function isDesign(v: unknown): v is Design {
  return typeof v === "string" && DESIGN_NAMES.has(v as Design);
}

function readStoredTheme(): ThemePreference {
  try {
    const saved = localStorage.getItem(KEY_THEME);
    if (isTheme(saved)) return saved;
    // Legacy migrations: "default" was the pre-Retro default; design
    // names stored under "editor.theme" come from the previous
    // single-axis implementation.
    if (saved === "default") return "system";
    if (isDesign(saved)) {
      // Adopt as a design and clear the theme key. The split happens
      // lazily so a user upgrading from the single-axis build sees
      // their existing "violet" still applied — just on a fresh
      // "system" theme underneath.
      try {
        localStorage.setItem(KEY_DESIGN, saved);
        localStorage.removeItem(KEY_THEME);
      } catch { /* ignore — we'll fall back to "system" */ }
      return "system";
    }
  } catch { /* localStorage may be blocked (sandboxed iframe, private mode). */ }
  return "system";
}

function readStoredDesign(): Design | null {
  try {
    const saved = localStorage.getItem(KEY_DESIGN);
    if (isDesign(saved)) return saved;
  } catch { /* see above */ }
  return null;
}

function prefersDark(): boolean {
  if (typeof window === "undefined" || !window.matchMedia) return false;
  return window.matchMedia("(prefers-color-scheme: dark)").matches;
}

function resolveTheme(pref: ThemePreference): "light" | "dark" | "retro" {
  if (pref === "system") return prefersDark() ? "dark" : "light";
  return pref;
}

function resolveActive(): ResolvedTheme {
  if (activeDesign) return activeDesign;
  return resolveTheme(activeTheme);
}

let activeTheme: ThemePreference = readStoredTheme();
let activeDesign: Design | null = readStoredDesign();

function applyAttr(resolved: ResolvedTheme) {
  if (typeof document === "undefined") return;
  if (resolved === "light") {
    document.documentElement.removeAttribute("data-theme");
  } else {
    document.documentElement.setAttribute("data-theme", resolved);
  }
}

applyAttr(resolveActive());

/** Set the theme axis. Picking a theme implicitly clears any active
 *  design — the click should always produce a visible change. */
export function setTheme(pref: ThemePreference) {
  const designCleared = activeDesign !== null;
  if (pref === activeTheme && !designCleared) return;
  activeTheme = pref;
  activeDesign = null;
  try {
    localStorage.setItem(KEY_THEME, pref);
    localStorage.removeItem(KEY_DESIGN);
  } catch { /* see above */ }
  applyAttr(resolveActive());
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent(EVENT_THEME, { detail: { name: pref } }));
    if (designCleared) {
      window.dispatchEvent(new CustomEvent(EVENT_DESIGN, { detail: { name: null } }));
    }
  }
}

export function getTheme(): ThemePreference {
  return activeTheme;
}

/** Set the design axis (the decorative palette overlay). The theme
 *  axis is unchanged — the user's brightness mode preference outlasts
 *  any design experiment. */
export function setDesign(d: Design) {
  if (d === activeDesign) return;
  activeDesign = d;
  try { localStorage.setItem(KEY_DESIGN, d); } catch { /* see above */ }
  applyAttr(resolveActive());
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent(EVENT_DESIGN, { detail: { name: d } }));
  }
}

/** Clear the design — chrome reverts to the theme axis underneath. */
export function clearDesign() {
  if (activeDesign === null) return;
  activeDesign = null;
  try { localStorage.removeItem(KEY_DESIGN); } catch { /* see above */ }
  applyAttr(resolveActive());
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent(EVENT_DESIGN, { detail: { name: null } }));
  }
}

export function getDesign(): Design | null {
  return activeDesign;
}

/** Resolved theme right now (system → light|dark; design > theme).
 *  Useful for code that needs to branch on the actual visual mode. */
export function getResolvedTheme(): ResolvedTheme {
  return resolveActive();
}

if (typeof window !== "undefined") {
  // Cross-tab/cross-frame propagation: storage events fire in OTHER
  // frames of the same origin when localStorage changes.
  window.addEventListener("storage", (e) => {
    if (e.key === KEY_THEME && isTheme(e.newValue) && e.newValue !== activeTheme) {
      activeTheme = e.newValue;
      applyAttr(resolveActive());
      window.dispatchEvent(new CustomEvent(EVENT_THEME, { detail: { name: e.newValue } }));
      return;
    }
    if (e.key === KEY_DESIGN) {
      const next = isDesign(e.newValue) ? e.newValue : null;
      if (next === activeDesign) return;
      activeDesign = next;
      applyAttr(resolveActive());
      window.dispatchEvent(new CustomEvent(EVENT_DESIGN, { detail: { name: next } }));
    }
  });

  // System-appearance changes propagate live when the theme axis is
  // "system" AND no design is overriding — flip dark↔light without a
  // refresh.
  if (window.matchMedia) {
    const mql = window.matchMedia("(prefers-color-scheme: dark)");
    const onChange = () => {
      if (activeTheme !== "system" || activeDesign !== null) return;
      applyAttr(resolveActive());
      window.dispatchEvent(new CustomEvent(EVENT_THEME, { detail: { name: activeTheme } }));
    };
    if (mql.addEventListener) mql.addEventListener("change", onChange);
    else if (mql.addListener) mql.addListener(onChange); // Safari < 14
  }
}

// Backwards-compat re-export so existing call sites that imported
// `ThemeName` keep compiling. New code should use ThemePreference.
export type ThemeName = ThemePreference;

/** Subscribe to theme-axis changes. Fires for explicit setTheme()
 *  calls and live OS appearance flips while "system" is selected.
 *  Returns an unsubscribe function. */
export function subscribeTheme(listener: (pref: ThemePreference) => void): () => void {
  if (typeof window === "undefined") return () => {};
  const handler = (e: Event) => {
    const detail = (e as CustomEvent<{ name?: ThemePreference }>).detail;
    if (detail?.name) listener(detail.name);
    else listener(activeTheme);
  };
  window.addEventListener(EVENT_THEME, handler);
  return () => window.removeEventListener(EVENT_THEME, handler);
}

/** Subscribe to design-axis changes. Fires for setDesign() and
 *  clearDesign() calls. The listener receives the new design, or null
 *  when cleared. */
export function subscribeDesign(listener: (d: Design | null) => void): () => void {
  if (typeof window === "undefined") return () => {};
  const handler = (e: Event) => {
    const detail = (e as CustomEvent<{ name?: Design | null }>).detail;
    listener(detail?.name ?? activeDesign);
  };
  window.addEventListener(EVENT_DESIGN, handler);
  return () => window.removeEventListener(EVENT_DESIGN, handler);
}
